### ISSUE TITLE
Some styles are not well adapted

### ISSUE THREAD

**Issue by djwlx** [DyingDown/hexo-theme-last#1]
<img width="102" alt="截屏2024-02-05 17 08 30" src="https://github.com/DyingDown/hexo-theme-last/assets/58622651/81ad9afc-4276-4d3f-9824-5fc69152ef7c">

**Comment by DyingDown** [comment]
Thanks for bringing this up. I have updated the new style.
![image](https://github.com/user-attachments/assets/d2d37e5b-f981-4b16-a383-4106a6caad74)
